/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param appliances List of all appliances' IDs comma separated
 */
data class _1ApplianceOrdersBody (

    /* List of all appliances' IDs comma separated */
    val appliances: kotlin.String
) {
}