/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param nickname Appliance name
 * @param model ApplianceModel ID if the appliance we're trying to create is included in IRDB.
 * @param modelType 
 * @param device Device ID
 * @param image Basename of the image file included in the app. Ex: \"ico_ac_1\" 
 */
data class _1AppliancesBody (

    /* Appliance name */
    val nickname: kotlin.String,
    /* ApplianceModel ID if the appliance we're trying to create is included in IRDB. */
    val model: kotlin.String? = null,
    val modelType: _1AppliancesBody.ModelType? = null,
    /* Device ID */
    val device: kotlin.String,
    /* Basename of the image file included in the app. Ex: \"ico_ac_1\"  */
    val image: kotlin.String
) {
    /**
    * 
    * Values: AC,TV,LIGHT
    */
    enum class ModelType(val value: kotlin.String){
        AC("AC"),
        TV("TV"),
        LIGHT("LIGHT");
    }
}