/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param message JSON serialized object describing infrared signals. Includes \"data\", \"freq\" and \"format\" keys.
 */
data class _1DetectapplianceBody (

    /* JSON serialized object describing infrared signals. Includes \"data\", \"freq\" and \"format\" keys. */
    val message: kotlin.String
) {
}