/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ACButton
import io.swagger.client.models.AirConRangeModes

/**
 * 
 * @param modes 
 * @param fixedButtons 
 */
data class AirConRange (

    val modes: AirConRangeModes? = null,
    val fixedButtons: kotlin.Array<ACButton>? = null
) {
}