/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AirDirection
import io.swagger.client.models.AirVolume
import io.swagger.client.models.Temperature

/**
 * 
 * @param temp 
 * @param vol 
 * @param dir 
 */
data class AirConRangeMode (

    val temp: kotlin.Array<Temperature>? = null,
    val vol: kotlin.Array<AirVolume>? = null,
    val dir: kotlin.Array<AirDirection>? = null
) {
}