/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AirConRangeMode

/**
 * 
 * @param cool 
 * @param warm 
 * @param dry 
 * @param blow 
 * @param auto 
 */
data class AirConRangeModes (

    val cool: AirConRangeMode? = null,
    val warm: AirConRangeMode? = null,
    val dry: AirConRangeMode? = null,
    val blow: AirConRangeMode? = null,
    val auto: AirConRangeMode? = null
) {
}