/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Empty means automatic. Numbers express the amount of volume. The range of AirVolumes which the air conditioner accepts depends on the air conditioner model and operation mode. Check the 'AirConRangeMode' information in the response for the range of the particular air conditioner model and operation mode.
 * Values: EMPTY,AUTO,_1,_2,_3,_4,_5,_6,_7,_8,_9,_10
 */
enum class AirVolume(val value: kotlin.String){
    EMPTY(""),// :/
    AUTO("auto"),// :/
    _1("1"),// :/
    _2("2"),// :/
    _3("3"),// :/
    _4("4"),// :/
    _5("5"),// :/
    _6("6"),// :/
    _7("7"),// :/
    _8("8"),// :/
    _9("9"),// :/
    _10("10");// :/
}