/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AirCon
import io.swagger.client.models.AirConParams
import io.swagger.client.models.ApplianceModel
import io.swagger.client.models.ApplianceType
import io.swagger.client.models.DeviceCore
import io.swagger.client.models.Id
import io.swagger.client.models.Image
import io.swagger.client.models.LIGHT
import io.swagger.client.models.Signal
import io.swagger.client.models.SmartMeter
import io.swagger.client.models.TV

/**
 * 
 * @param id 
 * @param device 
 * @param model 
 * @param nickname 
 * @param image 
 * @param type 
 * @param settings 
 * @param aircon 
 * @param signals 
 * @param tv 
 * @param light 
 * @param smartMeter 
 */
data class Appliance (

    val id: Id? = null,
    val device: DeviceCore? = null,
    val model: ApplianceModel? = null,
    val nickname: kotlin.String? = null,
    val image: Image? = null,
    val type: ApplianceType? = null,
    val settings: AirConParams? = null,
    val aircon: AirCon? = null,
    val signals: kotlin.Array<Signal>? = null,
    val tv: TV? = null,
    val light: LIGHT? = null,
    val smartMeter: SmartMeter? = null
) {
}