/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Type of the appliance. \"AC\" (Air conditioner), \"TV\" and \"LIGHT\" are 1st class citizen appliance, which is included in our IRDB (InfraRed signals DataBase). The \"ApplianceModel\" stores meta data about the appliance. We provide AC specific UI. Everything else is \"IR\". We just learn the signals from the remote and store them, and when users tap the button on the smartphone app, our server sends it through Remo.
 * Values: AC,TV,LIGHT,IR
 */
enum class ApplianceType(val value: kotlin.String){
    AC("AC"),// :/
    TV("TV"),// :/
    LIGHT("LIGHT"),// :/
    IR("IR");// :/
}