/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Id

/**
 * 
 * @param id 
 * @param name 
 * @param temperatureOffset 
 * @param humidityOffset 
 * @param createdAt 
 * @param updatedAt 
 * @param firmwareVersion 
 * @param macAddress 
 * @param serialNumber 
 */
data class DeviceCore (

    val id: Id? = null,
    val name: kotlin.String? = null,
    val temperatureOffset: java.math.BigDecimal? = null,
    val humidityOffset: java.math.BigDecimal? = null,
    val createdAt: java.time.LocalDateTime? = null,
    val updatedAt: java.time.LocalDateTime? = null,
    val firmwareVersion: kotlin.String? = null,
    val macAddress: kotlin.String? = null,
    val serialNumber: kotlin.String? = null
) {
}