/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param offset Humidity offset value added to the measured humidity.
 */
data class DeviceHumidityOffsetBody (

    /* Humidity offset value added to the measured humidity. */
    val offset: kotlin.Int
) {
}