/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param brightness 
 * @param power 
 * @param lastButton 
 */
data class LIGHTState (

    val brightness: kotlin.String? = null,
    val power: LIGHTState.Power? = null,
    val lastButton: kotlin.String? = null
) {
    /**
    * 
    * Values: ON,OFF
    */
    enum class Power(val value: kotlin.String){
        ON("on"),
        OFF("off");
    }
}