/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * The reference key to SensorValue means \"te\" = temperature, \"hu\" = humidity, \"il\" = illumination, \"mo\" = movement. The val of \"mo\" is always 1 and when movement event is captured created_at is updated. 
 * @param &#x60;val&#x60; 
 * @param createdAt 
 */
data class SensorValue (

    val `val`: kotlin.Float? = null,
    val createdAt: java.time.LocalDateTime? = null
) {
}