/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param image Basename of the image file included in the app. Ex: \"ico_io\" 
 * @param name Signal name
 */
data class SignalsSignalBody (

    /* Basename of the image file included in the app. Ex: \"ico_io\"  */
    val image: kotlin.String,
    /* Signal name */
    val name: kotlin.String
) {
}