/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.EchonetLiteProperty

/**
 * 
 * @param echonetliteProperties 
 */
data class SmartMeter (

    val echonetliteProperties: kotlin.Array<EchonetLiteProperty>? = null
) {
}