/**
 * Nature API
 * Read/Write Nature Remo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param input 
 */
data class TVState (

    val input: TVState.Input? = null
) {
    /**
    * 
    * Values: T,BS,CS
    */
    enum class Input(val value: kotlin.String){
        T("t"),
        BS("bs"),
        CS("cs");
    }
}